const countries = {
	"afghanistan": "AF",
	af: "AF",
	afg: "AF",
	"åland islands": "AX",
	ax: "AX",
	ala: "AX",
	"albania": "AL",
	al: "AL",
	alb: "AL",
	"algeria": "DZ",
	dz: "DZ",
	dza: "DZ",
	"american samoa": "AS",
	as: "AS",
	asm: "AS",
	"andorra": "AD",
	ad: "AD",
	and: "AD",
	"angola": "AO",
	ao: "AO",
	ago: "AO",
	"anguilla": "AI",
	ai: "AI",
	aia: "AI",
	"antarctica": "AQ",
	aq: "AQ",
	ata: "AQ",
	"antigua and barbuda": "AG",
	ag: "AG",
	atg: "AG",
	"argentina": "AR",
	ar: "AR",
	arg: "AR",
	"armenia": "AM",
	am: "AM",
	arm: "AM",
	"aruba": "AW",
	aw: "AW",
	abw: "AW",
	"australia": "AU",
	au: "AU",
	aus: "AU",
	"austria": "AT",
	at: "AT",
	aut: "AT",
	"azerbaijan": "AZ",
	az: "AZ",
	aze: "AZ",
	"bahamas": "BS",
	bs: "BS",
	bhs: "BS",
	"bahrain": "BH",
	bh: "BH",
	bhr: "BH",
	"bangladesh": "BD",
	bd: "BD",
	bgd: "BD",
	"barbados": "BB",
	bb: "BB",
	brb: "BB",
	"belarus": "BY",
	by: "BY",
	blr: "BY",
	"belgium": "BE",
	be: "BE",
	bel: "BE",
	"belize": "BZ",
	bz: "BZ",
	blz: "BZ",
	"benin": "BJ",
	bj: "BJ",
	ben: "BJ",
	"bermuda": "BM",
	bm: "BM",
	bmu: "BM",
	"bhutan": "BT",
	bt: "BT",
	btn: "BT",
	"bolivia": "BO",
	bo: "BO",
	bol: "BO",
	"bonaire, sint eustatius and saba": "BQ",
	bq: "BQ",
	bes: "BQ",
	"bosnia and herzegovina": "BA",
	ba: "BA",
	bih: "BA",
	"botswana": "BW",
	bw: "BW",
	bwa: "BW",
	"bouvet island": "BV",
	bv: "BV",
	bvt: "BV",
	"brazil": "BR",
	br: "BR",
	bra: "BR",
	"british indian ocean territory": "IO",
	io: "IO",
	iot: "IO",
	"brunei darussalam": "BN",
	bn: "BN",
	brn: "BN",
	"bulgaria": "BG",
	bg: "BG",
	bgr: "BG",
	"burkina faso": "BF",
	bf: "BF",
	bfa: "BF",
	"burundi": "BI",
	bi: "BI",
	bdi: "BI",
	"cabo verde": "CV",
	cv: "CV",
	cpv: "CV",
	"cambodia": "KH",
	kh: "KH",
	khm: "KH",
	"cameroon": "CM",
	cm: "CM",
	cmr: "CM",
	"canada": "CA",
	ca: "CA",
	can: "CA",
	"cayman islands": "KY",
	ky: "KY",
	cym: "KY",
	"central african republic": "CF",
	cf: "CF",
	caf: "CF",
	"chad": "TD",
	td: "TD",
	tcd: "TD",
	"chile": "CL",
	cl: "CL",
	chl: "CL",
	"china": "CN",
	cn: "CN",
	chn: "CN",
	"christmas island": "CX",
	cx: "CX",
	cxr: "CX",
	"cocos islands": "CC",
	cc: "CC",
	cck: "CC",
	"colombia": "CO",
	co: "CO",
	col: "CO",
	"comoros": "KM",
	km: "KM",
	com: "KM",
	"congo": "CG",
	cg: "CG",
	cog: "CG",
	"congo": "CD",
	cd: "CD",
	cod: "CD",
	"cook islands": "CK",
	ck: "CK",
	cok: "CK",
	"costa rica": "CR",
	cr: "CR",
	cri: "CR",
	"côte d'ivoire": "CI",
	ci: "CI",
	civ: "CI",
	"croatia": "HR",
	hr: "HR",
	hrv: "HR",
	"cuba": "CU",
	cu: "CU",
	cub: "CU",
	"curaçao": "CW",
	cw: "CW",
	cuw: "CW",
	"cyprus": "CY",
	cy: "CY",
	cyp: "CY",
	"czech republic": "CZ",
	cz: "CZ",
	cze: "CZ",
	"denmark": "DK",
	dk: "DK",
	dnk: "DK",
	"djibouti": "DJ",
	dj: "DJ",
	dji: "DJ",
	"dominica": "DM",
	dm: "DM",
	dma: "DM",
	"dominican republic": "DO",
	do: "DO",
	dom: "DO",
	"ecuador": "EC",
	ec: "EC",
	ecu: "EC",
	"egypt": "EG",
	eg: "EG",
	egy: "EG",
	"el salvador": "SV",
	sv: "SV",
	slv: "SV",
	"equatorial guinea": "GQ",
	gq: "GQ",
	gnq: "GQ",
	"eritrea": "ER",
	er: "ER",
	eri: "ER",
	"estonia": "EE",
	ee: "EE",
	est: "EE",
	"ethiopia": "ET",
	et: "ET",
	eth: "ET",
	"falkland islands": "FK",
	fk: "FK",
	flk: "FK",
	"faroe islands": "FO",
	fo: "FO",
	fro: "FO",
	"fiji": "FJ",
	fj: "FJ",
	fji: "FJ",
	"finland": "FI",
	fi: "FI",
	fin: "FI",
	"france": "FR",
	fr: "FR",
	fra: "FR",
	"french guiana": "GF",
	gf: "GF",
	guf: "GF",
	"french polynesia": "PF",
	pf: "PF",
	pyf: "PF",
	"french southern territories": "TF",
	tf: "TF",
	atf: "TF",
	"gabon": "GA",
	ga: "GA",
	gab: "GA",
	"gambia": "GM",
	gm: "GM",
	gmb: "GM",
	"georgia": "GE",
	ge: "GE",
	geo: "GE",
	"germany": "DE",
	de: "DE",
	deu: "DE",
	"ghana": "GH",
	gh: "GH",
	gha: "GH",
	"gibraltar": "GI",
	gi: "GI",
	gib: "GI",
	"greece": "GR",
	gr: "GR",
	grc: "GR",
	"greenland": "GL",
	gl: "GL",
	grl: "GL",
	"grenada": "GD",
	gd: "GD",
	grd: "GD",
	"guadeloupe": "GP",
	gp: "GP",
	glp: "GP",
	"guam": "GU",
	gu: "GU",
	gum: "GU",
	"guatemala": "GT",
	gt: "GT",
	gtm: "GT",
	"guernsey": "GG",
	gg: "GG",
	ggy: "GG",
	"guinea": "GN",
	gn: "GN",
	gin: "GN",
	"guinea-bissau": "GW",
	gw: "GW",
	gnb: "GW",
	"guyana": "GY",
	gy: "GY",
	guy: "GY",
	"haiti": "HT",
	ht: "HT",
	hti: "HT",
	"heard island and mcdonald islands": "HM",
	hm: "HM",
	hmd: "HM",
	"holy see": "VA",
	va: "VA",
	vat: "VA",
	"honduras": "HN",
	hn: "HN",
	hnd: "HN",
	"hong kong": "HK",
	hk: "HK",
	hkg: "HK",
	"hungary": "HU",
	hu: "HU",
	hun: "HU",
	"iceland": "IS",
	is: "IS",
	isl: "IS",
	"india": "IN",
	in: "IN",
	ind: "IN",
	"indonesia": "ID",
	id: "ID",
	idn: "ID",
	"islamic republic of iran": "IR",
	ir: "IR",
	irn: "IR",
	"iraq": "IQ",
	iq: "IQ",
	irq: "IQ",
	"ireland": "IE",
	ie: "IE",
	irl: "IE",
	"isle of man": "IM",
	im: "IM",
	imn: "IM",
	"israel": "IL",
	il: "IL",
	isr: "IL",
	"italy": "IT",
	it: "IT",
	ita: "IT",
	"jamaica": "JM",
	jm: "JM",
	jam: "JM",
	"japan": "JP",
	jp: "JP",
	jpn: "JP",
	"jersey": "JE",
	je: "JE",
	jey: "JE",
	"jordan": "JO",
	jo: "JO",
	jor: "JO",
	"kazakhstan": "KZ",
	kz: "KZ",
	kaz: "KZ",
	"kenya": "KE",
	ke: "KE",
	ken: "KE",
	"kiribati": "KI",
	ki: "KI",
	kir: "KI",
	"democratic people's republic of korea": "KP",
	kp: "KP",
	prk: "KP",
	"republic of korea": "KR",
	kr: "KR",
	kor: "KR",
	"kuwait": "KW",
	kw: "KW",
	kwt: "KW",
	"kyrgyzstan": "KG",
	kg: "KG",
	kgz: "KG",
	"lao people's democratic republic": "LA",
	la: "LA",
	lao: "LA",
	"latvia": "LV",
	lv: "LV",
	lva: "LV",
	"lebanon": "LB",
	lb: "LB",
	lbn: "LB",
	"lesotho": "LS",
	ls: "LS",
	lso: "LS",
	"liberia": "LR",
	lr: "LR",
	lbr: "LR",
	"libya": "LY",
	ly: "LY",
	lby: "LY",
	"liechtenstein": "LI",
	li: "LI",
	lie: "LI",
	"lithuania": "LT",
	lt: "LT",
	ltu: "LT",
	"luxembourg": "LU",
	lu: "LU",
	lux: "LU",
	"macao": "MO",
	mo: "MO",
	mac: "MO",
	"macedonia": "MK",
	mk: "MK",
	mkd: "MK",
	"madagascar": "MG",
	mg: "MG",
	mdg: "MG",
	"malawi": "MW",
	mw: "MW",
	mwi: "MW",
	"malaysia": "MY",
	my: "MY",
	mys: "MY",
	"maldives": "MV",
	mv: "MV",
	mdv: "MV",
	"mali": "ML",
	ml: "ML",
	mli: "ML",
	"malta": "MT",
	mt: "MT",
	mlt: "MT",
	"marshall islands": "MH",
	mh: "MH",
	mhl: "MH",
	"martinique": "MQ",
	mq: "MQ",
	mtq: "MQ",
	"mauritania": "MR",
	mr: "MR",
	mrt: "MR",
	"mauritius": "MU",
	mu: "MU",
	mus: "MU",
	"mayotte": "YT",
	yt: "YT",
	myt: "YT",
	"mexico": "MX",
	mx: "MX",
	mex: "MX",
	"federated states of micronesia": "FM",
	fm: "FM",
	fsm: "FM",
	"republic of moldova": "MD",
	md: "MD",
	mda: "MD",
	"monaco": "MC",
	mc: "MC",
	mco: "MC",
	"mongolia": "MN",
	mn: "MN",
	mng: "MN",
	"montenegro": "ME",
	me: "ME",
	mne: "ME",
	"montserrat": "MS",
	ms: "MS",
	msr: "MS",
	"morocco": "MA",
	ma: "MA",
	mar: "MA",
	"mozambique": "MZ",
	mz: "MZ",
	moz: "MZ",
	"myanmar": "MM",
	mm: "MM",
	mmr: "MM",
	"namibia": "NA",
	na: "NA",
	nam: "NA",
	"nauru": "NR",
	nr: "NR",
	nru: "NR",
	"nepal": "NP",
	np: "NP",
	npl: "NP",
	"netherlands": "NL",
	nl: "NL",
	nld: "NL",
	"new caledonia": "NC",
	nc: "NC",
	ncl: "NC",
	"new zealand": "NZ",
	nz: "NZ",
	nzl: "NZ",
	"nicaragua": "NI",
	ni: "NI",
	nic: "NI",
	"niger": "NE",
	ne: "NE",
	ner: "NE",
	"nigeria": "NG",
	ng: "NG",
	nga: "NG",
	"niue": "NU",
	nu: "NU",
	niu: "NU",
	"norfolk island": "NF",
	nf: "NF",
	nfk: "NF",
	"northern mariana islands": "MP",
	mp: "MP",
	mnp: "MP",
	"norway": "NO",
	no: "NO",
	nor: "NO",
	"oman": "OM",
	om: "OM",
	omn: "OM",
	"pakistan": "PK",
	pk: "PK",
	pak: "PK",
	"palau": "PW",
	pw: "PW",
	plw: "PW",
	"state of palestine": "PS",
	ps: "PS",
	pse: "PS",
	"panama": "PA",
	pa: "PA",
	pan: "PA",
	"papua new guinea": "PG",
	pg: "PG",
	png: "PG",
	"paraguay": "PY",
	py: "PY",
	pry: "PY",
	"peru": "PE",
	pe: "PE",
	per: "PE",
	"philippines": "PH",
	ph: "PH",
	phl: "PH",
	"pitcairn": "PN",
	pn: "PN",
	pcn: "PN",
	"poland": "PL",
	pl: "PL",
	pol: "PL",
	"portugal": "PT",
	pt: "PT",
	prt: "PT",
	"puerto rico": "PR",
	pr: "PR",
	pri: "PR",
	"qatar": "QA",
	qa: "QA",
	qat: "QA",
	"réunion": "RE",
	re: "RE",
	reu: "RE",
	"romania": "RO",
	ro: "RO",
	rou: "RO",
	"russian federation": "RU",
	ru: "RU",
	rus: "RU",
	"rwanda": "RW",
	rw: "RW",
	rwa: "RW",
	"saint barthélemy": "BL",
	bl: "BL",
	blm: "BL",
	"saint helena, ascension and tristan da cunha": "SH",
	sh: "SH",
	shn: "SH",
	"saint kitts and nevis": "KN",
	kn: "KN",
	kna: "KN",
	"saint lucia": "LC",
	lc: "LC",
	lca: "LC",
	"saint martin": "MF",
	mf: "MF",
	maf: "MF",
	"saint pierre and miquelon": "PM",
	pm: "PM",
	spm: "PM",
	"saint vincent and the grenadines": "VC",
	vc: "VC",
	vct: "VC",
	"samoa": "WS",
	ws: "WS",
	wsm: "WS",
	"san marino": "SM",
	sm: "SM",
	smr: "SM",
	"sao tome and principe": "ST",
	st: "ST",
	stp: "ST",
	"saudi arabia": "SA",
	sa: "SA",
	sau: "SA",
	"senegal": "SN",
	sn: "SN",
	sen: "SN",
	"serbia": "RS",
	rs: "RS",
	srb: "RS",
	"seychelles": "SC",
	sc: "SC",
	syc: "SC",
	"sierra leone": "SL",
	sl: "SL",
	sle: "SL",
	"singapore": "SG",
	sg: "SG",
	sgp: "SG",
	"sint maarten": "SX",
	sx: "SX",
	sxm: "SX",
	"slovakia": "SK",
	sk: "SK",
	svk: "SK",
	"slovenia": "SI",
	si: "SI",
	svn: "SI",
	"solomon islands": "SB",
	sb: "SB",
	slb: "SB",
	"somalia": "SO",
	so: "SO",
	som: "SO",
	"south africa": "ZA",
	za: "ZA",
	zaf: "ZA",
	"south georgia and the south sandwich islands": "GS",
	gs: "GS",
	sgs: "GS",
	"south sudan": "SS",
	ss: "SS",
	ssd: "SS",
	"spain": "ES",
	es: "ES",
	esp: "ES",
	"sri lanka": "LK",
	lk: "LK",
	lka: "LK",
	"sudan": "SD",
	sd: "SD",
	sdn: "SD",
	"suriname": "SR",
	sr: "SR",
	sur: "SR",
	"svalbard and jan mayen": "SJ",
	sj: "SJ",
	sjm: "SJ",
	"swaziland": "SZ",
	sz: "SZ",
	swz: "SZ",
	"sweden": "SE",
	se: "SE",
	swe: "SE",
	"switzerland": "CH",
	ch: "CH",
	che: "CH",
	"syrian arab republic": "SY",
	sy: "SY",
	syr: "SY",
	"taiwan, province of china": "TW",
	tw: "TW",
	twn: "TW",
	"tajikistan": "TJ",
	tj: "TJ",
	tjk: "TJ",
	"united republic of tanzania": "TZ",
	tz: "TZ",
	tza: "TZ",
	"thailand": "TH",
	th: "TH",
	tha: "TH",
	"timor-leste": "TL",
	tl: "TL",
	tls: "TL",
	"togo": "TG",
	tg: "TG",
	tgo: "TG",
	"tokelau": "TK",
	tk: "TK",
	tkl: "TK",
	"tonga": "TO",
	to: "TO",
	ton: "TO",
	"trinidad and tobago": "TT",
	tt: "TT",
	tto: "TT",
	"tunisia": "TN",
	tn: "TN",
	tun: "TN",
	"turkey": "TR",
	tr: "TR",
	tur: "TR",
	"turkmenistan": "TM",
	tm: "TM",
	tkm: "TM",
	"turks and caicos islands": "TC",
	tc: "TC",
	tca: "TC",
	"tuvalu": "TV",
	tv: "TV",
	tuv: "TV",
	"uganda": "UG",
	ug: "UG",
	uga: "UG",
	"ukraine": "UA",
	ua: "UA",
	ukr: "UA",
	"united arab emirates": "AE",
	ae: "AE",
	are: "AE",
	"united kingdom of great britain and northern ireland": "GB",
    gb: "GB",
	gbr: "GB",
	"united states of america": "US",
	us: "US",
	usa: "US",
	"united states minor outlying islands": "UM",
	um: "UM",
	umi: "UM",
	"uruguay": "UY",
	uy: "UY",
	ury: "UY",
	"uzbekistan": "UZ",
	uz: "UZ",
	uzb: "UZ",
	"vanuatu": "VU",
	vu: "VU",
	vut: "VU",
	"venezuela (bolivarian republic of)": "VE",
	ve: "VE",
	ven: "VE",
	"viet nam": "VN",
	vn: "VN",
	vnm: "VN",
	"virgin islands": "VG",
	vg: "VG",
	vgb: "VG",
	"virgin islands of the united states": "VI",
	vi: "VI",
	vir: "VI",
	"wallis and futuna": "WF",
	wf: "WF",
	wlf: "WF",
	"western sahara": "EH",
	eh: "EH",
	esh: "EH",
	"yemen": "YE",
	ye: "YE",
	yem: "YE",
	"zambia": "ZM",
	zm: "ZM",
	zmb: "ZM",
	"zimbabwe": "ZW",
	zw: "ZW",
	zwe: "ZW",

    // a few special cases, add your own if you need to
    uk: "GB",
    "united kingdom": "GB",
    england: "GB",
    "united states": "US",
	"venezuela": "VE",
	"north korea": "KP",
	"south korea": "KR",
    "korea": "KR",
	"iran": "IR",
};
